export default interface ApplicationProgram {
  id: string,
  applicant_id: string,
  company_name: string,
  program_id: string,
  program_name: string,
  job_title: string,
  firstName: string,
  lastName: string,
  email_profile: string,
  birthDate: string,
  gender: string,
  address: string,
  phone: string,
  resume: string,
  transcript: string,
  portfolio: string,
  status: string,
}
